plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
masthead_title: "Health Care TCM Treatment Center"
include:
  - index.md
  - products
  # - CONTRIBUTING.md
  # - LICENSE.md
  # - COPYING.md
  # - CODE_OF_CONDUCT.md
  # - CONTRIBUTING.md
  # - ISSUE_TEMPLATE.md
  # - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-tactile
